name: Publish to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm test
        continue-on-error: true

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - name: Update version from release
        run: |
          echo "Debug: GITHUB_REF is $GITHUB_REF"
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          echo "Debug: Extracted RELEASE_VERSION is $RELEASE_VERSION"
          CLEAN_VERSION=${RELEASE_VERSION#v}
          echo "Debug: Cleaned CLEAN_VERSION is $CLEAN_VERSION"

          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Debug: Current package.json version is $CURRENT_VERSION"

          if [ "$CLEAN_VERSION" = "$CURRENT_VERSION" ]; then
            echo "Version $CLEAN_VERSION is already set in package.json. Skipping update."
          else
            echo "Updating version to $CLEAN_VERSION"
            npm version $CLEAN_VERSION --no-git-tag-version
          fi
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
